#!/usr/bin/env python3
"""Build symbols.js for the overlay from xcompose-stem's docs/xcompose_sequences.json.

Each entry: e = the symbol, n = its name, s = the compose sequence as typed,
k = lowercase search text (name, sequence, category, codepoint).
"""
import json, sys

GLYPH = {
    "asciicircum": "^", "underscore": "_", "minus": "-", "greater": ">", "less": "<",
    "equal": "=", "plus": "+", "asterisk": "*", "slash": "/", "colon": ":", "period": ".",
    "comma": ",", "apostrophe": "'", "quotedbl": '"', "exclam": "!", "question": "?",
    "parenleft": "(", "parenright": ")", "bracketleft": "[", "bracketright": "]",
    "braceleft": "{", "braceright": "}", "asciitilde": "~", "grave": "`", "bar": "|",
    "backslash": "\\", "dollar": "$", "percent": "%", "ampersand": "&", "at": "@",
    "numbersign": "#", "semicolon": ";", "space": "␣",
}

# Short chip labels for the picker, keyed by the section name as it appears in
# xcompose-stem after title-casing. Anything unmapped keeps its full name.
GROUP = {
    "Math / Logic / Sets": "Math",
    "Higher Logic / Category Theory / Long Arrows": "Logic",
    "Superscripts & Subscripts": "Sub/Super",
    "Greek Letters": "Greek",
    "Ipa": "IPA",
    "Box-Drawing": "Box",
    "Ui Symbols & Shapes": "UI",
    "Currency": "Currency",
    "Units & Measurements": "Units",
    "Typography & Spacing": "Typography",
    "Calligraphic / Fraktur": "Script",
    "Astronomy": "Astronomy",
    "Smart Quotes": "Quotes",
    "Music Symbols": "Music",
    "Chemistry": "Chemistry",
    "International Punctuation": "Punctuation",
    "International Diacritics": "Diacritics",
    "Legal / Document Symbols": "Legal",
}

# One key per chip, pressed with Alt. Where a group has an xcompose prefix the
# letter is that prefix (g h k b u), so the chip key and the compose key agree;
# the rest take a free letter. 0 is All and z is the Unicode long tail; both
# are handled by the overlay, not the data.
GROUP_KEY = {
    "Greek": "g", "Math": "h", "Logic": "l", "Sub/Super": "s", "Typography": "t",
    "Quotes": "q", "Punctuation": "p", "Diacritics": "d", "Units": "n",
    "Chemistry": "c", "Astronomy": "a", "IPA": "i", "Script": "f", "UI": "k",
    "Box": "b", "Music": "u", "Currency": "m", "Legal": "e",
}

def main(src, dst):
    data = json.load(open(src, encoding="utf-8"))
    # One tile per symbol: xcompose-stem lists several sequences for some
    # symbols (≤ is both "< =" and "= <"); the first keeps the tile and the
    # later ones add their keys to its search string.
    out = []
    by_symbol = {}
    for q in data["sequences"]:
        keys = [GLYPH.get(k, k) for k in q["keys"]]
        seq = " ".join(keys)
        name = q.get("comment") or ""
        cat = (q.get("category") or "").split("(")[0].strip().title()
        k = " ".join([name, seq, "".join(keys), cat, q.get("subcategory") or "", "u+" + (q.get("codepoint") or "")]).lower()
        group = GROUP.get(cat, cat)
        have = by_symbol.get(q["symbol"])
        if have:
            extra = " ".join([seq, "".join(keys)]).lower()
            if extra not in have["k"]:
                have["k"] += " " + extra
            continue
        item = {"e": q["symbol"], "n": name, "s": seq, "c": cat, "g": group, "k": k + " " + group.lower()}
        by_symbol[q["symbol"]] = item
        out.append(item)
    groups = []
    for item in out:
        if item["g"] not in groups: groups.append(item["g"])
    with open(dst, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/generate.py from xcompose-stem's xcompose_sequences.json. Do not edit.\n")
        f.write("var SYMBOLS = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n")
        f.write("var GROUPS = " + json.dumps(groups, ensure_ascii=False) + ";\n")
        keys = {g: GROUP_KEY[g] for g in groups if g in GROUP_KEY}
        assert len(set(keys.values())) == len(keys), "duplicate chip keys"
        f.write("var GROUP_KEYS = " + json.dumps(keys, ensure_ascii=False) + ";\n")
    print(f"{len(out)} symbols -> {dst}")

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "../xcompose-stem/docs/xcompose_sequences.json",
         sys.argv[2] if len(sys.argv) > 2 else "symbols.js")
